### ISSUE TITLE
Add github auth token

### ISSUE THREAD

**Issue by fengb** [fengb/zigbot9001#6]
Unauthenticated Github API requests get throttled at 60 requests per hour. By adding an auth, similar to Discord auth, we effectively have "unlimited" requests.

Need to add a `github_auth_token` field onto the context and add it to the Github request header.

**Comment by travisstaloch** [comment]
note: in case you haven't created one yet, you can create a gh access token from Settings / Developer Settings / Personal Access Tokens.  I created one with no scopes which seems to work fine for this application.  Then copy the token into your .env as GITHUB_AUTH=$token
